/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
          './pages/**/*.{js,ts,jsx,tsx,mdx}',
          './components/**/*.{js,ts,jsx,tsx,mdx}',
          './app/**/*.{js,ts,jsx,tsx,mdx}',
        ],
    theme: {
          extend: {
                  fontFamily: {
                            sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
                  },
                  colors: {
                            primary: {
                                        50:  '#eef2ff',
                                        100: '#e0e7ff',
                                        200: '#c7d2fe',
                                        500: '#6366f1',
                                        600: '#4f46e5',
                                        700: '#4338ca',
                                        DEFAULT: '#6366f1',
                            },
                            sidebar: {
                                        bg:     '#0f172a',
                                        hover:  '#1e293b',
                                        active: '#1e293b',
                                        text:   'rgba(255,255,255,0.55)',
                                        'text-active': '#ffffff',
                            },
                            gray: {
                                        50:  '#f8fafc',
                                        100: '#f1f5f9',
                                        200: '#e2e8f0',
                                        300: '#cbd5e1',
                                        400: '#94a3b8',
                                        500: '#64748b',
                                        600: '#475569',
                                        700: '#334155',
                                        800: '#1e293b',
                                        900: '#0f172a',
                            },
                            surface:    '#ffffff',
                            background: '#f8fafc',
                            border:     '#e2e8f0',
                            'text-primary':   '#0f172a',
                            'text-secondary': '#64748b',
                            'text-muted':     '#94a3b8',
                            success: { DEFAULT: '#10b981', light: '#d1fae5', dark: '#065f46' },
                            warning: { DEFAULT: '#f59e0b', light: '#fef3c7', dark: '#92400e' },
                            danger:  { DEFAULT: '#ef4444', light: '#fee2e2', dark: '#991b1b' },
                            info:    { DEFAULT: '#3b82f6', light: '#dbeafe', dark: '#1e40af' },
                  },
                  borderRadius: {
                            sm: '4px',
                            DEFAULT: '6px',
                            md: '8px',
                            lg: '12px',
                            xl: '16px',
                            full: '9999px',
                  },
                  boxShadow: {
                            xs:  '0 1px 2px rgba(15,23,42,0.05)',
                            sm:  '0 1px 3px rgba(15,23,42,0.08), 0 1px 2px rgba(15,23,42,0.04)',
                            DEFAULT: '0 4px 6px rgba(15,23,42,0.06), 0 2px 4px rgba(15,23,42,0.04)',
                            md:  '0 4px 12px rgba(15,23,42,0.10), 0 2px 6px rgba(15,23,42,0.04)',
                            lg:  '0 10px 25px rgba(15,23,42,0.12), 0 4px 10px rgba(15,23,42,0.06)',
                            none: 'none',
                  },
          },
    },
    plugins: [],
}
